aws:
  bucket_name: pwcgstin
  credentials:
    aws_access_key_id: minioadmin
    aws_secret_access_key: minioadmin
  endpoint_url: http://127.0.0.1:9000
config_file: config.yaml
configurations:
  allow_open_input_file: true
  console: true
  rabbit_message_in_console: true
  theme: dark
db:
  company:
  - !!python/tuple
    - Generic
    - generic
  - !!python/tuple
    - Reload
    - reload
  - !!python/tuple
    - TML
    - tml
  data_type:
  - !!python/tuple
    - '""'
    - '""'
  db_name: pwc_test_db
  file_sub_type:
  - !!python/tuple
    - '""'
    - '""'
  file_type:
  - !!python/tuple
    - ICEGATE -1
    - icegate sanctioned scrolls
  - !!python/tuple
    - ICEGATE -2
    - icegate pending scrolls
  - !!python/tuple
    - Bank Register
    - Bank Register
  - !!python/tuple
    - Checklist BOE
    - checklist bill of entry
  - !!python/tuple
    - Bill Of Entry
    - bill of entry
  folder_name: ''
rabbit:
  credentials:
    password: valhala
    username: prajwal
  rabbit_queue_name:
  - !!python/tuple
    - uploaded-file-message-queue
    - uploaded-file-message-queue
  server:
    host: 127.1.1.0
    port: '5672'
    virtual_host: /
